# Generated by Django 4.1.5 on 2023-01-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('acronym', models.CharField(max_length=2)),
                ('woeid', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
